{
 "title": "Messaging App Overview",
 "description": "Dashboard providing a complete overview of the messaging platform, including service-specific metrics for authentication, messaging, and online presence, as well as infrastructure metrics such as CPU and memory usage per node. Enables real-time monitoring and observability of system health and operational behavior.",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage per Node",
   "type": "timeseries",
   "description": "Shows the current CPU usage of each Node in CPU cores.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Application Pod",
   "type": "timeseries",
   "description": "Displays the current CPU usage of each application Pod in CPU cores. Only Pods belonging to the application are shown.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (\n    rate(container_cpu_usage_seconds_total{\n      pod=~\"authservice.*|messageservice.*|onlineservice.*|frontend.*\"\n    }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Working Set per Node",
   "type": "timeseries",
   "description": "Displays the actual memory actively used by containers on each Node in MiB, excluding cache memory that can be freed. Provides a more accurate view of memory usage per Node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (node) (container_memory_working_set_bytes{container!=\"POD\", container!=\"\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Working Set per Application Pod",
   "type": "timeseries",
   "description": "Displays the actual memory actively used by each application Pod in MiB, excluding cache memory that can be freed. Only Pods belonging to the application are shown.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{\n    pod=~\"authservice.*|messageservice.*|onlineservice.*|frontend.*\"\n  }\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Authentication Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Authentication Service Metrics",
   "type": "timeseries",
   "description": "Aggregated total number of successful and failed user logins and registrations for the Authentication Service, across all active Pods. Provides a clear view of authentication activity over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(auth_registration_success_total)",
     "legendFormat": "Successful Registrations"
    },
    {
     "expr": "sum(auth_registration_failure_total)",
     "legendFormat": "Registration Failure"
    },
    { "expr": "sum(auth_login_success_total)", "legendFormat": "Login Success" },
    { "expr": "sum(auth_login_failure_total)", "legendFormat": "Login Failure" }
   ]
  },
  { "title": "Messaging Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Message Service Metrics",
   "type": "timeseries",
   "description": "Aggregated total number of messages sent, failed message attempts, and group chats created across all active MessageService Pods. Provides a clear view of messaging activity over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "sum(messages_sent_total)", "legendFormat": "Messages Sent" },
    { "expr": "sum(messages_failed_total)", "legendFormat": "Messages Failed" },
    { "expr": "sum(groupchats_created_total)", "legendFormat": "Group Chats Created" }
   ]
  },
  { "title": "Online Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Online Service Metrics",
   "type": "timeseries",
   "description": "Displays the total number of heartbeats received and the current number of users marked as online, aggregated across all active OnlineService Pods. Provides real-time visibility into user presence and connectivity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(online_heartbeats_total[1m]))",
     "legendFormat": "Heartbeats Received Per Second"
    },
    { "expr": "sum(online_users_current)", "legendFormat": "Users Online" }
   ]
  }
 ]
}