apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: onlineservice-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: onlineservice
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
